### ISSUE TITLE
Mixing front-end with back-end code

### ISSUE THREAD

**Issue by szepeviktor** [sikessem/starter#2]
In the `app` directory front-end is mixed with back-end.
It would be cleaner to have the Laravel skeleton default `app` for PHP and `resources` for the front-end.

**Comment by szepeviktor** [comment]
Also for the CI workflow. It would be nice to have a separate workflow for the back-end, and one for the front-end.
They are very different animals 🐘 one runs on a server, the other in a browser.

**Comment by siguici** [comment]
> In the `app` directory front-end is mixed with back-end. It would be cleaner to have the Laravel skeleton default `app` for PHP and `resources` for the front-end.

Solved ([#279a564](https://github.com/sikessem/starter/commit/9d81b625066062ed37633de7be966576148d5203))

**Comment by szepeviktor** [comment]
All right.
